In [1]:
import pandas as pd
df=pd.read_csv('E:\Machine Learning\Sundhar sir lecture\Melbourne_housing_FULL.csv')
df=df.drop(['Address','Method','Date','Bedroom2','Distance','Lattitude','Longtitude','YearBuilt','SellerG'],axis=1)
df.dropna(subset = ['Landsize'], inplace=True)
df['Car'].fillna(value=0,inplace=True)
df['Bathroom'].fillna(value=1,inplace=True)
df

Suburb  Rooms Type      Price  Postcode  Bathroom  Car  Landsize  \
0      Abbotsford      2    h        NaN    3067.0       1.0  1.0     126.0   
1      Abbotsford      2    h  1480000.0    3067.0       1.0  1.0     202.0   
2      Abbotsford      2    h  1035000.0    3067.0       1.0  0.0     156.0   
3      Abbotsford      3    u        NaN    3067.0       2.0  1.0       0.0   
4      Abbotsford      3    h  1465000.0    3067.0       2.0  0.0     134.0   
...           ...    ...  ...        ...       ...       ...  ...       ...   
34851  Yarraville      3    h  1101000.0    3013.0       1.0  0.0     288.0   
34852  Yarraville      4    h  1480000.0    3013.0       1.0  3.0     593.0   
34853  Yarraville      2    h   888000.0    3013.0       2.0  1.0      98.0   
34854  Yarraville      2    t   705000.0    3013.0       1.0  2.0     220.0   
34856  Yarraville      2    h  1020000.0    3013.0       1.0  0.0     250.0   

       BuildingArea               CouncilArea             Regionname  \
0               NaN        Yarra City Council  Northern Metropolitan   
1               NaN        Yarra City Council  Northern Metropolitan   
2              79.0        Yarra City Council  Northern Metropolitan   
3               NaN        Yarra City Council  Northern Metropolitan   
4             150.0        Yarra City Council  Northern Metropolitan   
...             ...                       ...                    ...   
34851           NaN  Maribyrnong City Council   Western Metropolitan   
34852           NaN  Maribyrnong City Council   Western Metropolitan   
34853         104.0  Maribyrnong City Council   Western Metropolitan   
34854         120.0  Maribyrnong City Council   Western Metropolitan   
34856         103.0  Maribyrnong City Council   Western Metropolitan   

       Propertycount  
0             4019.0  
1             4019.0  
2             4019.0  
3             4019.0  
4             4019.0  
...              ...  
34851         6543.0  
34852         6543.0  
34853         6543.0  
34854         6543.0  
34856         6543.0  

[23047 rows x 12 columns]

In [2]:
import numpy as np
df['result'] = np.where(df['Landsize'] >= df['BuildingArea'],df['Landsize'],df['BuildingArea'])
# df

In [3]:
df['Landsize'] = np.where(df['Landsize']==0 ,df['BuildingArea'],df['Landsize'])
df=df.drop('BuildingArea',axis=1)
df=df.drop('result',axis=1)
df.sort_values('Landsize',ascending=True,inplace=True)
df.dropna(subset=['Landsize'],inplace=True)
df=df.iloc[100:]
#df.sort_values('Price',ascending=True,inplace=True)
df

Suburb  Rooms Type      Price  Postcode  Bathroom  Car  Landsize  \
10276     Thornbury      1    u   365000.0    3071.0       1.0  1.0      40.0   
7406      Northcote      2    t        NaN    3070.0       2.0  1.0      40.0   
8827       Richmond      1    u   390000.0    3121.0       1.0  1.0      40.0   
10360     Thornbury      1    u   330000.0    3071.0       1.0  1.0      40.0   
2961       Carnegie      1    u        NaN    3163.0       1.0  1.0      40.0   
...             ...    ...  ...        ...       ...       ...  ...       ...   
17293        Silvan      3    h  1085000.0    3795.0       2.0  2.0   76000.0   
32577  Diggers Rest      4    h        NaN    3427.0       2.0  0.0   80000.0   
24800      Wildwood      5    h  1030000.0    3429.0       2.0  2.0   89030.0   
26868  Bullengarook      4    h  1050000.0    3437.0       2.0  1.0  146699.0   
18036       Fitzroy      3    h  2700000.0    3065.0       3.0  1.0  433014.0   

                        CouncilArea             Regionname  Propertycount  
10276          Darebin City Council  Northern Metropolitan         8870.0  
7406           Darebin City Council  Northern Metropolitan        11364.0  
8827             Yarra City Council  Northern Metropolitan        14949.0  
10360          Darebin City Council  Northern Metropolitan         8870.0  
2961         Glen Eira City Council  Southern Metropolitan         7822.0  
...                             ...                    ...            ...  
17293    Yarra Ranges Shire Council       Eastern Victoria          457.0  
32577             Hume City Council   Western Metropolitan         1184.0  
24800             Hume City Council   Western Metropolitan           83.0  
26868  Macedon Ranges Shire Council      Northern Victoria          249.0  
18036            Yarra City Council  Northern Metropolitan         5825.0  

[21837 rows x 11 columns]

In [4]:
df.isna().sum()

Suburb              0
Rooms               0
Type                0
Price            4811
Postcode            0
Bathroom            0
Car                 0
Landsize            0
CouncilArea         0
Regionname          0
Propertycount       0
dtype: int64

In [5]:
df.sort_values('Price',ascending=False,inplace=True)
df.dropna(subset=['Price'],inplace=True)
df

Suburb  Rooms Type       Price  Postcode  Bathroom  Car  Landsize  \
25635    Brighton      4    h  11200000.0    3186.0       3.0  2.0    1400.0   
19583    Mulgrave      3    h   9000000.0    3170.0       1.0  1.0     744.0   
12539  Canterbury      5    h   8000000.0    3126.0       5.0  4.0    2079.0   
15696    Hawthorn      4    h   7650000.0    3122.0       2.0  4.0    1690.0   
5937          Kew      6    h   6500000.0    3101.0       6.0  3.0    1334.0   
...           ...    ...  ...         ...       ...       ...  ...       ...   
11848      Albion      1    u    185000.0    3020.0       1.0  1.0    2347.0   
21012   Brunswick      1    u    170000.0    3056.0       1.0  0.0    1250.0   
12947    Hawthorn      1    u    160000.0    3122.0       1.0  0.0     322.0   
3290       Coburg      4    h    145000.0    3058.0       1.0  1.0     536.0   
3063    Caulfield      4    h    131000.0    3162.0       1.0  2.0     499.0   

                   CouncilArea                  Regionname  Propertycount  
25635     Bayside City Council       Southern Metropolitan        10579.0  
19583      Monash City Council  South-Eastern Metropolitan         7113.0  
12539  Boroondara City Council       Southern Metropolitan         3265.0  
15696  Boroondara City Council       Southern Metropolitan        11308.0  
5937   Boroondara City Council       Southern Metropolitan        10331.0  
...                        ...                         ...            ...  
11848    Brimbank City Council        Western Metropolitan         2185.0  
21012    Moreland City Council       Northern Metropolitan        11918.0  
12947  Boroondara City Council       Southern Metropolitan        11308.0  
3290      Darebin City Council       Northern Metropolitan        11204.0  
3063    Glen Eira City Council       Southern Metropolitan         2379.0  

[17026 rows x 11 columns]

In [6]:

df = df[['Rooms','Propertycount','Postcode','Bathroom','Car','Landsize','Type','CouncilArea','Regionname','Suburb','Price']]
df=df.reset_index(drop=True)
df

Rooms  Propertycount  Postcode  Bathroom  Car  Landsize Type  \
0          4        10579.0    3186.0       3.0  2.0    1400.0    h   
1          3         7113.0    3170.0       1.0  1.0     744.0    h   
2          5         3265.0    3126.0       5.0  4.0    2079.0    h   
3          4        11308.0    3122.0       2.0  4.0    1690.0    h   
4          6        10331.0    3101.0       6.0  3.0    1334.0    h   
...      ...            ...       ...       ...  ...       ...  ...   
17021      1         2185.0    3020.0       1.0  1.0    2347.0    u   
17022      1        11918.0    3056.0       1.0  0.0    1250.0    u   
17023      1        11308.0    3122.0       1.0  0.0     322.0    u   
17024      4        11204.0    3058.0       1.0  1.0     536.0    h   
17025      4         2379.0    3162.0       1.0  2.0     499.0    h   

                   CouncilArea                  Regionname      Suburb  \
0         Bayside City Council       Southern Metropolitan    Brighton   
1          Monash City Council  South-Eastern Metropolitan    Mulgrave   
2      Boroondara City Council       Southern Metropolitan  Canterbury   
3      Boroondara City Council       Southern Metropolitan    Hawthorn   
4      Boroondara City Council       Southern Metropolitan         Kew   
...                        ...                         ...         ...   
17021    Brimbank City Council        Western Metropolitan      Albion   
17022    Moreland City Council       Northern Metropolitan   Brunswick   
17023  Boroondara City Council       Southern Metropolitan    Hawthorn   
17024     Darebin City Council       Northern Metropolitan      Coburg   
17025   Glen Eira City Council       Southern Metropolitan   Caulfield   

            Price  
0      11200000.0  
1       9000000.0  
2       8000000.0  
3       7650000.0  
4       6500000.0  
...           ...  
17021    185000.0  
17022    170000.0  
17023    160000.0  
17024    145000.0  
17025    131000.0  

[17026 rows x 11 columns]

In [7]:
# new data frame with split value columns
new = df["CouncilArea"].str.split(" ", n = 1, expand = True)
new1 = df["Regionname"].str.split(" ", n = 1, expand = True)
# making separate first name column from new data frame
df["Council"]= new[0]
df["Region"]= new1[0]
  
# making separate last name column from new data frame
# df["Last Name"]= new[1]

df.drop(columns =["CouncilArea",'Regionname'], inplace = True)
df = df[['Rooms','Propertycount','Postcode','Bathroom','Car','Landsize','Type','Council','Region','Suburb','Price']]

# Dropping old Name columns
# data.drop(columns =["Name"], inplace = True)
df

Rooms  Propertycount  Postcode  Bathroom  Car  Landsize Type  \
0          4        10579.0    3186.0       3.0  2.0    1400.0    h   
1          3         7113.0    3170.0       1.0  1.0     744.0    h   
2          5         3265.0    3126.0       5.0  4.0    2079.0    h   
3          4        11308.0    3122.0       2.0  4.0    1690.0    h   
4          6        10331.0    3101.0       6.0  3.0    1334.0    h   
...      ...            ...       ...       ...  ...       ...  ...   
17021      1         2185.0    3020.0       1.0  1.0    2347.0    u   
17022      1        11918.0    3056.0       1.0  0.0    1250.0    u   
17023      1        11308.0    3122.0       1.0  0.0     322.0    u   
17024      4        11204.0    3058.0       1.0  1.0     536.0    h   
17025      4         2379.0    3162.0       1.0  2.0     499.0    h   

          Council         Region      Suburb       Price  
0         Bayside       Southern    Brighton  11200000.0  
1          Monash  South-Eastern    Mulgrave   9000000.0  
2      Boroondara       Southern  Canterbury   8000000.0  
3      Boroondara       Southern    Hawthorn   7650000.0  
4      Boroondara       Southern         Kew   6500000.0  
...           ...            ...         ...         ...  
17021    Brimbank        Western      Albion    185000.0  
17022    Moreland       Northern   Brunswick    170000.0  
17023  Boroondara       Southern    Hawthorn    160000.0  
17024     Darebin       Northern      Coburg    145000.0  
17025        Glen       Southern   Caulfield    131000.0  

[17026 rows x 11 columns]

In [8]:
# Assigning Values
x=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

# getting dummies
d1=pd.get_dummies(x[:,6])
d2=pd.get_dummies(x[:,7])
d3=pd.get_dummies(x[:,8])
d4=pd.get_dummies(x[:,9])

# Adding Dummies ,assigning to df , dropping original, concatenating, renaming, droping last column of dummies
x=pd.DataFrame(x)
x.drop([3,6,7,8,9],inplace=True,axis=1)
x=pd.concat([x,d1,d2,d3,d4],axis=1)
x.rename(columns={0:'Rooms',1:'Propertycount',2:'Bathroom',5:'Landsize',4:'Car'},inplace=True)
x.drop(['u','Yarra','Western','Yarraville'],inplace=True,axis=1)
x

Rooms Propertycount Bathroom  Car Landsize  h  t  Banyule  Bayside  \
0         4       10579.0   3186.0  2.0   1400.0  1  0        0        1   
1         3        7113.0   3170.0  1.0    744.0  1  0        0        0   
2         5        3265.0   3126.0  4.0   2079.0  1  0        0        0   
3         4       11308.0   3122.0  4.0   1690.0  1  0        0        0   
4         6       10331.0   3101.0  3.0   1334.0  1  0        0        0   
...     ...           ...      ...  ...      ... .. ..      ...      ...   
17021     1        2185.0   3020.0  1.0   2347.0  0  0        0        0   
17022     1       11918.0   3056.0  0.0   1250.0  0  0        0        0   
17023     1       11308.0   3122.0  0.0    322.0  0  0        0        0   
17024     4       11204.0   3058.0  1.0    536.0  1  0        0        0   
17025     4        2379.0   3162.0  2.0    499.0  1  0        0        0   

       Boroondara  ...  Wildwood  Williams Landing  Williamstown  \
0               0  ...         0                 0             0   
1               0  ...         0                 0             0   
2               1  ...         0                 0             0   
3               1  ...         0                 0             0   
4               1  ...         0                 0             0   
...           ...  ...       ...               ...           ...   
17021           0  ...         0                 0             0   
17022           0  ...         0                 0             0   
17023           1  ...         0                 0             0   
17024           0  ...         0                 0             0   
17025           0  ...         0                 0             0   

       Williamstown North  Windsor  Wollert  Wonga Park  Wyndham Vale  \
0                       0        0        0           0             0   
1                       0        0        0           0             0   
2                       0        0        0           0             0   
3                       0        0        0           0             0   
4                       0        0        0           0             0   
...                   ...      ...      ...         ...           ...   
17021                   0        0        0           0             0   
17022                   0        0        0           0             0   
17023                   0        0        0           0             0   
17024                   0        0        0           0             0   
17025                   0        0        0           0             0   

       Yallambie  Yarra Glen  
0              0           0  
1              0           0  
2              0           0  
3              0           0  
4              0           0  
...          ...         ...  
17021          0           0  
17022          0           0  
17023          0           0  
17024          0           0  
17025          0           0  

[17026 rows x 374 columns]

In [9]:
d1

h  t  u
0      1  0  0
1      1  0  0
2      1  0  0
3      1  0  0
4      1  0  0
...   .. .. ..
17021  0  0  1
17022  0  0  1
17023  0  0  1
17024  1  0  0
17025  1  0  0

[17026 rows x 3 columns]

In [10]:
d2

Banyule  Bayside  Boroondara  Brimbank  Cardinia  Casey  Darebin  \
0            0        1           0         0         0      0        0   
1            0        0           0         0         0      0        0   
2            0        0           1         0         0      0        0   
3            0        0           1         0         0      0        0   
4            0        0           1         0         0      0        0   
...        ...      ...         ...       ...       ...    ...      ...   
17021        0        0           0         1         0      0        0   
17022        0        0           0         0         0      0        0   
17023        0        0           1         0         0      0        0   
17024        0        0           0         0         0      0        1   
17025        0        0           0         0         0      0        0   

       Frankston  Glen  Greater  ...  Moonee  Moorabool  Moreland  Nillumbik  \
0              0     0        0  ...       0          0         0          0   
1              0     0        0  ...       0          0         0          0   
2              0     0        0  ...       0          0         0          0   
3              0     0        0  ...       0          0         0          0   
4              0     0        0  ...       0          0         0          0   
...          ...   ...      ...  ...     ...        ...       ...        ...   
17021          0     0        0  ...       0          0         0          0   
17022          0     0        0  ...       0          0         1          0   
17023          0     0        0  ...       0          0         0          0   
17024          0     0        0  ...       0          0         0          0   
17025          0     1        0  ...       0          0         0          0   

       Port  Stonnington  Whitehorse  Whittlesea  Wyndham  Yarra  
0         0            0           0           0        0      0  
1         0            0           0           0        0      0  
2         0            0           0           0        0      0  
3         0            0           0           0        0      0  
4         0            0           0           0        0      0  
...     ...          ...         ...         ...      ...    ...  
17021     0            0           0           0        0      0  
17022     0            0           0           0        0      0  
17023     0            0           0           0        0      0  
17024     0            0           0           0        0      0  
17025     0            0           0           0        0      0  

[17026 rows x 32 columns]

In [11]:
d3

Eastern  Northern  South-Eastern  Southern  Western
0            0         0              0         1        0
1            0         0              1         0        0
2            0         0              0         1        0
3            0         0              0         1        0
4            0         0              0         1        0
...        ...       ...            ...       ...      ...
17021        0         0              0         0        1
17022        0         1              0         0        0
17023        0         0              0         1        0
17024        0         1              0         0        0
17025        0         0              0         1        0

[17026 rows x 5 columns]

In [12]:
d4

Abbotsford  Aberfeldie  Airport West  Albanvale  Albert Park  Albion  \
0               0           0             0          0            0       0   
1               0           0             0          0            0       0   
2               0           0             0          0            0       0   
3               0           0             0          0            0       0   
4               0           0             0          0            0       0   
...           ...         ...           ...        ...          ...     ...   
17021           0           0             0          0            0       1   
17022           0           0             0          0            0       0   
17023           0           0             0          0            0       0   
17024           0           0             0          0            0       0   
17025           0           0             0          0            0       0   

       Alphington  Altona  Altona Meadows  Altona North  ...  \
0               0       0               0             0  ...   
1               0       0               0             0  ...   
2               0       0               0             0  ...   
3               0       0               0             0  ...   
4               0       0               0             0  ...   
...           ...     ...             ...           ...  ...   
17021           0       0               0             0  ...   
17022           0       0               0             0  ...   
17023           0       0               0             0  ...   
17024           0       0               0             0  ...   
17025           0       0               0             0  ...   

       Williams Landing  Williamstown  Williamstown North  Windsor  Wollert  \
0                     0             0                   0        0        0   
1                     0             0                   0        0        0   
2                     0             0                   0        0        0   
3                     0             0                   0        0        0   
4                     0             0                   0        0        0   
...                 ...           ...                 ...      ...      ...   
17021                 0             0                   0        0        0   
17022                 0             0                   0        0        0   
17023                 0             0                   0        0        0   
17024                 0             0                   0        0        0   
17025                 0             0                   0        0        0   

       Wonga Park  Wyndham Vale  Yallambie  Yarra Glen  Yarraville  
0               0             0          0           0           0  
1               0             0          0           0           0  
2               0             0          0           0           0  
3               0             0          0           0           0  
4               0             0          0           0           0  
...           ...           ...        ...         ...         ...  
17021           0             0          0           0           0  
17022           0             0          0           0           0  
17023           0             0          0           0           0  
17024           0             0          0           0           0  
17025           0             0          0           0           0  

[17026 rows x 333 columns]

In [13]:
x['Rooms']=x['Rooms'].astype('float64')
x['Propertycount']=x['Propertycount'].astype('float64')
x['Bathroom']=x['Bathroom'].astype('float64')
x['Car']=x['Car'].astype('float64')
x['Landsize']=x['Landsize'].astype('float64')

In [14]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17026 entries, 0 to 17025
Columns: 374 entries, Rooms to Yarra Glen
dtypes: float64(5), uint8(369)
memory usage: 6.6 MB


In [15]:
from statsmodels.stats.outliers_influence import variance_inflation_factor
x['intercept']=1
vif = pd.DataFrame()
vif['variables']=x.columns
vif['vif'] = [variance_inflation_factor(x.values,i) for i in range(x.shape[1])]

C:\Users\SSN\anaconda3\lib\site-packages\statsmodels\stats\outliers_influence.py:193: RuntimeWarning: divide by zero encountered in double_scalars
  vif = 1. / (1. - r_squared_i)
C:\Users\SSN\anaconda3\lib\site-packages\statsmodels\regression\linear_model.py:1715: RuntimeWarning: divide by zero encountered in double_scalars
  return 1 - self.ssr/self.centered_tss


In [17]:
# vif.to_csv(r'E:\Projects\ML\Melb House Price Prediction\3.csv')

In [ ]:
x.drop('intercept',axis=1,inplace=True)

In [ ]:
# df.to_csv('E:\Projects\ML\Melb House Price Prediction\cleaned_df.csv')

In [18]:
from sklearn.linear_model import LinearRegression
reg=LinearRegression()

Rooms  Propertycount  Bathroom  Car  Landsize  h  t  Banyule  Bayside  \
0        4.0        10579.0    3186.0  2.0    1400.0  1  0        0        1   
1        3.0         7113.0    3170.0  1.0     744.0  1  0        0        0   
2        5.0         3265.0    3126.0  4.0    2079.0  1  0        0        0   
3        4.0        11308.0    3122.0  4.0    1690.0  1  0        0        0   
4        6.0        10331.0    3101.0  3.0    1334.0  1  0        0        0   
...      ...            ...       ...  ...       ... .. ..      ...      ...   
17021    1.0         2185.0    3020.0  1.0    2347.0  0  0        0        0   
17022    1.0        11918.0    3056.0  0.0    1250.0  0  0        0        0   
17023    1.0        11308.0    3122.0  0.0     322.0  0  0        0        0   
17024    4.0        11204.0    3058.0  1.0     536.0  1  0        0        0   
17025    4.0         2379.0    3162.0  2.0     499.0  1  0        0        0   

       Boroondara  ...  Williams Landing  Williamstown  Williamstown North  \
0               0  ...                 0             0                   0   
1               0  ...                 0             0                   0   
2               1  ...                 0             0                   0   
3               1  ...                 0             0                   0   
4               1  ...                 0             0                   0   
...           ...  ...               ...           ...                 ...   
17021           0  ...                 0             0                   0   
17022           0  ...                 0             0                   0   
17023           1  ...                 0             0                   0   
17024           0  ...                 0             0                   0   
17025           0  ...                 0             0                   0   

       Windsor  Wollert  Wonga Park  Wyndham Vale  Yallambie  Yarra Glen  \
0            0        0           0             0          0           0   
1            0        0           0             0          0           0   
2            0        0           0             0          0           0   
3            0        0           0             0          0           0   
4            0        0           0             0          0           0   
...        ...      ...         ...           ...        ...         ...   
17021        0        0           0             0          0           0   
17022        0        0           0             0          0           0   
17023        0        0           0             0          0           0   
17024        0        0           0             0          0           0   
17025        0        0           0             0          0           0   

       intercept  
0              1  
1              1  
2              1  
3              1  
4              1  
...          ...  
17021          1  
17022          1  
17023          1  
17024          1  
17025          1  

[17026 rows x 375 columns]

In [20]:
x

Rooms  Propertycount  Bathroom  Car  Landsize  h  t  Banyule  Bayside  \
0        4.0        10579.0    3186.0  2.0    1400.0  1  0        0        1   
1        3.0         7113.0    3170.0  1.0     744.0  1  0        0        0   
2        5.0         3265.0    3126.0  4.0    2079.0  1  0        0        0   
3        4.0        11308.0    3122.0  4.0    1690.0  1  0        0        0   
4        6.0        10331.0    3101.0  3.0    1334.0  1  0        0        0   
...      ...            ...       ...  ...       ... .. ..      ...      ...   
17021    1.0         2185.0    3020.0  1.0    2347.0  0  0        0        0   
17022    1.0        11918.0    3056.0  0.0    1250.0  0  0        0        0   
17023    1.0        11308.0    3122.0  0.0     322.0  0  0        0        0   
17024    4.0        11204.0    3058.0  1.0     536.0  1  0        0        0   
17025    4.0         2379.0    3162.0  2.0     499.0  1  0        0        0   

       Boroondara  ...  Williams Landing  Williamstown  Williamstown North  \
0               0  ...                 0             0                   0   
1               0  ...                 0             0                   0   
2               1  ...                 0             0                   0   
3               1  ...                 0             0                   0   
4               1  ...                 0             0                   0   
...           ...  ...               ...           ...                 ...   
17021           0  ...                 0             0                   0   
17022           0  ...                 0             0                   0   
17023           1  ...                 0             0                   0   
17024           0  ...                 0             0                   0   
17025           0  ...                 0             0                   0   

       Windsor  Wollert  Wonga Park  Wyndham Vale  Yallambie  Yarra Glen  \
0            0        0           0             0          0           0   
1            0        0           0             0          0           0   
2            0        0           0             0          0           0   
3            0        0           0             0          0           0   
4            0        0           0             0          0           0   
...        ...      ...         ...           ...        ...         ...   
17021        0        0           0             0          0           0   
17022        0        0           0             0          0           0   
17023        0        0           0             0          0           0   
17024        0        0           0             0          0           0   
17025        0        0           0             0          0           0   

       intercept  
0              1  
1              1  
2              1  
3              1  
4              1  
...          ...  
17021          1  
17022          1  
17023          1  
17024          1  
17025          1  

[17026 rows x 375 columns]

In [21]:
y

array([11200000.,  9000000.,  8000000., ...,   160000.,   145000.,
         131000.])

In [26]:
from sklearn.model_selection import train_test_split
x_train, x_test,y_train,y_test = train_test_split(x,y,test_size=0.25, random_state=0)


In [34]:
x_train

array([[-2.82244756, -0.26224235,  0.63710973, ..., -0.64480566,
         0.03576402, -0.52940238],
       [ 2.43867365, -1.57250498, -0.48346776, ...,  0.94770977,
         0.52804454, -2.95257853],
       [-0.34992739,  0.56595439, -0.68251251, ...,  0.86489805,
         0.24203443, -1.61983345],
       ...,
       [ 0.82621261,  3.06994735, -2.2831978 , ..., -1.80923992,
        -0.93815777,  0.93212455],
       [ 2.29189861,  1.77572671,  4.50547538, ..., -0.65761705,
        -2.92971003,  0.21927902],
       [-2.03903655, -0.84058924, -0.18198224, ...,  0.26820119,
         0.25119095,  3.06313311]])

In [35]:
x_test

array([[-2.95874477, -0.343689  ,  0.43227401, ...,  0.83093764,
        -1.80549581, -0.34984162],
       [-1.994847  , -1.67791813, -0.77168836, ...,  0.12191429,
        -0.19241388,  2.27913185],
       [-3.63907932, -0.81898647,  1.95539188, ..., -2.61780778,
         0.45572162, -0.33188544],
       ...,
       [ 2.30965227, -1.58509376,  0.05531138, ...,  0.54359055,
        -0.75290556,  0.15893942],
       [-2.64056703,  0.05975339,  0.75711721, ..., -0.58923355,
        -0.12452406, -0.58499404],
       [-2.07385942, -0.90719139, -0.36725529, ...,  0.37254058,
         0.12375175,  2.94094464]])

In [36]:
y_train

array([ 765000., 1770000.,  980000., ...,  855000.,  800000., 1630100.])

In [37]:
y_test

array([1150000.,  700000.,  572000., ..., 1450000.,  860000.,  961000.])

In [32]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

from sklearn.decomposition import PCA
pca = PCA()
x_train = pca.fit_transform(x_train)
x_test = pca.transform(x_test)

pca = PCA(n_components=8)
x_train = pca.fit_transform(x_train)
x_test = pca.transform(x_test)

In [33]:
pca.explained_variance_ratio_


array([0.00963279, 0.00897123, 0.00823059, 0.00737514, 0.00658597,
       0.00642771, 0.00584008, 0.00557587])

In [38]:
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import BaggingRegressor

In [41]:
reg = LinearRegression()
#bag = BaggingRegressor()

In [40]:
#regres='Linear Regression'

In [42]:
reg.fit(x_train,y_train)

LinearRegression()

In [45]:
predicted=reg.predict(x_test)
predicted

array([ 890058.61198434,  718767.74315571,  937350.28859715, ...,
       1674889.68248662,  903723.00426005,  714986.37577293])

In [47]:
from sklearn.metrics import r2_score, mean_squared_error
import math
math.sqrt(mean_squared_error(y_test, predicted))

571613.5589845374

In [49]:
from sklearn import metrics
rmse = np.sqrt(metrics.mean_squared_error(y_test, predicted))
rmse

571613.5589845374

In [52]:
r2 = metrics.r2_score(y_test, predicted)
r2

0.24698095021714472